language: node_js
node_js:
    - "9"
    - "10"
install:
    - npm install --save-dev
before_script:
    - npm version
    - node --version
    - npm ls
script:
    - npm run travis
after_success:
    - node scripts/travis.js succeeded
after_failure:
    - node scripts/travis.js failed
sudo: true
